on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aksazurecontainer.azurecr.io
        username: ${{ secrets.acr_aksazurecontainer_username }}
        password: ${{ secrets.acr_aksazurecontainer_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/StudentAdmissionService" -f  "StudentAdmissionService/Dockerfile" -t aksazurecontainer.azurecr.io/aksschoolcluster:${{ github.sha }} --label dockerfile-path=StudentAdmissionService/Dockerfile
        docker push aksazurecontainer.azurecr.io/aksschoolcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksschoolcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aksschoolclusterb21b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aksschoolclusterb21b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aksschoolclusterb21b
        container-registry-url: aksazurecontainer.azurecr.io
        container-registry-username: ${{ secrets.acr_aksazurecontainer_username }}
        container-registry-password: ${{ secrets.acr_aksazurecontainer_password }}
        secret-name: aksschoolcludockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aksschoolclusterb21b
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          aksazurecontainer.azurecr.io/aksschoolcluster:${{ github.sha }}
        imagepullsecrets: |
          aksschoolcludockerauth
